model_params:
  name: 'VanillaVAE'
  in_genes: 1000
  latent_dim: 128
  bs: 8


data_params:
  data_path: "Data/"
  train_batch_size: 8
  val_batch_size:  8
  num_workers: 4


exp_params:
  LR: 0.002
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: []
  max_epochs: 5

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  