data_path: ../data/final/d0_log_rle.csv
ds_name: d0
label_path: ../data/final/labels_final_0.csv
output_dir: ../results/final/ML/d0
trained_models:
- log_reg
use_flux: false
use_gs: false
use_pca: false
use_resampling: false
used_unit: log_rle
