data_path: ../data/final/d10_log_rle.csv
ds_name: d10
label_path: ../data/final/labels_final_10.csv
output_dir: ../results/final/ML/d10
trained_models:
- gbm
use_flux: false
use_gs: false
use_pca: false
used_unit: log_rle
