data_path: ../data/final/d11_log_rle.csv
ds_name: d11
label_path: ../data/final/labels_final_11.csv
output_dir: ../results/final/ML/d11
trained_models:
- xgb
use_flux: false
use_gs: false
use_pca: false
used_unit: log_rle
