data_path: ../data/final/d11_log_tpm.csv
ds_name: d11
label_path: ../data/final/labels_final_11.csv
output_dir: ../results/final/ML/d11
trained_models:
- log_reg
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tpm
