data_path: ../data/final/d14_log_rle.csv
ds_name: d14
label_path: ../data/final/labels_final_14.csv
output_dir: ../results/final/ML/d14
trained_models:
- log_reg
use_flux: false
use_gs: false
use_pca: false
used_unit: log_rle
