data_path: ../data/final/d15_log_tpm.csv
ds_name: d15
label_path: ../data/final/labels_final_15.csv
output_dir: ../results/final/ML/d15
trained_models:
- rf
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tpm
