data_path: ../data/final/d2_log_tmm.csv
ds_name: d2
label_path: ../data/final/labels_final_2.csv
output_dir: ../results/final/ML/d2
trained_models:
- rf
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tmm
