data_path: ../data/final/d3_log_cnt.csv
ds_name: d3
label_path: ../data/final/labels_final_3.csv
output_dir: ../results/final/ML/d3
trained_models:
- log_reg
use_flux: false
use_gs: false
use_pca: false
used_unit: log_cnt
