data_path: ../data/final/d4_log_tpm.csv
ds_name: d4
label_path: ../data/final/labels_final_4.csv
output_dir: ../results/final/ML/d4
trained_models:
- mlp
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tpm
