data_path: ../data/final/d7_log_rle.csv
ds_name: d7
label_path: ../data/final/labels_final_7.csv
output_dir: ../results/final/ML/d7
trained_models:
- rf
use_flux: false
use_gs: false
use_pca: false
used_unit: log_rle
