data_path: ../data/final/d8_log_tmm.csv
ds_name: d8
label_path: ../data/final/labels_final_8.csv
output_dir: ../results/final/ML/d8
trained_models:
- log_reg
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tmm
