data_path: ../data/final/d9_log_tpm.csv
ds_name: d9
label_path: ../data/final/labels_final_9.csv
output_dir: ../results/final/ML/d9
trained_models:
- mlp
use_flux: false
use_gs: false
use_pca: false
used_unit: log_tpm
